apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telemetry

  template:
    metadata:
      labels:
        app: telemetry

    spec:
      containers:
        - name: telemetry
          image: acrmicrodev2606.azurecr.io/axion-telemetryq-uery-service:v02
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: telemetry
spec:
  type: LoadBalancer
  selector:
    app: telemetry

  ports:
    - port: 80
      targetPort: 8000