apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telemetry

  template:
    metadata:
      labels:
        app: telemetry

    spec:
      containers:
        - name: telemetry
          image: acrmicrodev2606.azurecr.io/telemetry:v1
          ports:
            - containerPort: 8000
