apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service
  labels:
    app: ingestion-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-service

  template:
    metadata:
      labels:
        app: ingestion-service

    spec:
      containers:
        - name: ingestion-service-pod
          image: acrmicrodev2606.azurecr.io/injection:v1
          ports:
            - containerPort: 8000
